### ISSUE TITLE
create_swagger_config fails with KeyError on cygwin

### ISSUE THREAD

**Issue by franshamk** [Isilon/isilon_sdk#20]
Using python 2.7.8 under babun (cygwin) I get python failures. The identical command works fine on CentOS 7, python 2.7.9. Not urgent, just FYI. 

```
{ isilon_sdk } master » python components/create_swagger_config.py -i [REDACTED] -o onefs_8.0_swagger.json

Please provide the username used to access [REDACTED] via PAPI: [REDACTED]
Password:
Traceback (most recent call last):
  File "components/create_swagger_config.py", line 1228, in <module>
    main()
  File "components/create_swagger_config.py", line 1104, in main
    excludeEndPoints)
  File "components/create_swagger_config.py", line 903, in GetEndpointPaths
    numEndPoints = len(endPointListJson["directory"])
KeyError: 'directory'
{ isilon_sdk } master » python -V                                         ~/swagger2/isilon_sdk 1
Python 2.7.8
```

**Comment by apecoraro** [comment]
What does the resp object that gets returned from the requests.get(...) call on line 897 look like? I'm guessing that for some reason the GET query returned something other than a list of end points, which I'm guessing is due to differences in how the requests package works in Python 2.7.8 versus Python 2.7.9.

**Comment by franshamk** [comment]
Might have been an environmental hiccup. I added a print statement for the object, but now it's working fine. No errors anymore. Thanks!
